apiVersion: v1
kind: Service
metadata:
  name: artifacts-storage-console
  namespace: mlflow
spec:
  type: NodePort
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 32100
  selector:
    app: artifacts-storage
