apiVersion: v1
kind: Service
metadata:
  name: metadata-storage-console
  namespace: mlflow
spec:
  type: NodePort
  ports:
  - port: 5433
    protocol: TCP
    targetPort: 80
    nodePort: 32200
  selector:
    app: metadata-storage-console
