apiVersion: v1
kind: Service
metadata:
  name: mlflow-artifacts-server
  namespace: mlflow
spec:
  ports:
  - port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: mlflow-artifacts-server
