apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-storage
  namespace: mlflow
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: localhost/k8s-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-storage
  template:
    metadata:
      labels:
        app: metadata-storage
    spec:
      serviceAccountName: mlflow
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: metadata-storage
        image: metadata-storage
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: metadata-storage-secret
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: [CHOWN, DAC_OVERRIDE, FOWNER, FSETID, KILL, SETGID, SETUID, SETPCAP, NET_BIND_SERVICE, NET_RAW, SYS_CHROOT, MKNOD, AUDIT_WRITE, SETFCAP]
        volumeMounts:
        - mountPath: /home/application
          name: application-volume
          readOnly: false
        - mountPath: /var/lib/postgresql/data
          name: postgresql-lib-volume
          readOnly: false
        - mountPath: /var/run/postgresql
          name: postgresql-run-volume
          readOnly: false
        startupProbe:
          exec:
            command:
            - rm
            - -rf
            - /bin/*
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
      volumes:
      - name: application-volume
        emptyDir: {}
      - name: postgresql-lib-volume
        emptyDir: {}
      - name: postgresql-run-volume
        emptyDir: {}
